using Microsoft.EntityFrameworkCore;

namespace ContactManager.Models
{
    public class ContactContext : DbContext 
    {
        public ContactContext(DbContextOptions<ContactContext> options)
            : base(options)
        { }

        // used by EF Core to generate database tables with the specified name
        // assignes a nullable value
        public DbSet<Contacts> Contacts { get; set; } = null!;

        public DbSet<Category> Category { get; set; } = null!;

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);


            modelBuilder.Entity<Category>().HasData(
                new Category { CategoryId = "R", Name = "Relatives" },
                new Category { CategoryId = "W", Name = "Work" },
                new Category { CategoryId = "F", Name = "Friends" },
                new Category { CategoryId = "O", Name = "Other" } );



            modelBuilder.Entity<Contacts>().HasData(
                new Contacts
                {
                    Id = 1,
                    First = "Smith", // not autogenerated in initial seeding
                    Last = "Nielson",
                    Phone = "801-555-777",
                    Email = "smith@gmail.com",
                    CategoryId = "W",
                    DateTime = DateTime.Now,
                    Organization = "Utah Valley University"

                },
                new Contacts
                {
                    Id = 2,
                    First = "Sam", // not autogenerated in initial seeding
                    Last = "Samuels",
                    Phone = "801-555-444",
                    Email = "sam@gmail.com",
                    CategoryId = "F",
                    DateTime = DateTime.Now,
                    Organization = null


                },
                new Contacts
                {
                    Id = 3,
                    First = "Rob", // not autogenerated in initial seeding
                    Last = "Roberts",
                    Phone = "801-555-666",
                    Email = "rob@gmail.com",
                    CategoryId = "R",
                    DateTime = DateTime.Now,
                    Organization = null

                }
            );
        }

    }
}
